### ISSUE TITLE
Legacy PCI intX don't appear to be triggering

### ISSUE THREAD

**Issue by jlintonarm** [SolidRun/edk2-platforms#2]
Due to issues with ACPI/MSI at the moment the kernel is falling back to legacy PCI intX. The nvidia GPU appears to be OOPsing because when a monitor is plugged in, it expects to receive interrupts and the linux /proc/interrupts shows that none are being delivered.

**Comment by jnettlet** [comment]
In the current root port hidden mode legacy interrupts are not available to the host OS because they belong to the root port.  This is a limitation of the implementation, and will be fixed with the new Arm PCIe SMC code.
