### ISSUE TITLE
ASSERT at PciCpuIo2Dxe.c and and video artifacts with GT710

### ISSUE THREAD

**Issue by samerhaj** [SolidRun/edk2-platforms#9]
when using the GT710 (ZOTAC GeForce® GT 710 1GB DDR3 PCIE x 1 , https://www.newegg.com/p/1FT-000M-002G0?Item=9SIA4UBAP85871) two issues are seen:

1. ASSERT at PciCpuIo2Dxe.c(406) 
2. Video artifacts (Refresh and rendering issues)

Skipping the ASSERTs work around the first issue.

The same is not observed with AMD Radeon RX560 (https://www.amazon.com/gp/product/B072VH8NR5/)

**Comment by samerhaj** [comment]
This is also related to #4 . Seems that using a custom driver with workarounds/changes me be the culprit.

**Comment by jnettlet** [comment]
This has been fixed and is available in the latest release
